tree_structure/employees/urls.py
from django.urls import path

from employees import views

urlpatterns = [
    path('', views.show_employees, name='show_employees'),
    path('employees/', views.show_employees, name='show_employees'),
    path('change_boss/', views.change_boss, name='change_boss'),
    path('employees_all/', views.show_employees_all, name='show_employees_all'),
    path('edit/<employee_id>/', views.edit, name='edit'),
    path('delete/<employee_id>/', views.delete, name='delete'),
]

tree_structure/tree_structure/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('employees.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

tree_structure/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

tree_structure/employees/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey


class Worker(MPTTModel):
    full_name = models.CharField(max_length=200,
                                 unique=True,
                                 verbose_name='ФИО'
                                 )
    position = models.CharField(max_length=200,
                                verbose_name='Должность'
                                )
    employment_date = models.DateTimeField(auto_now_add=False,
                                           verbose_name='Дата найма')
    salary = models.DecimalField(max_digits=15,
                                 decimal_places=2,
                                 verbose_name='Размер заработной платы',
                                 )
    date_added = models.DateTimeField(auto_now_add=True)

    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True,
                            blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['full_name']

    def __str__(self):
        return f'{self.id}, {self.full_name}, {self.position}'

tree_structure/users/models.py
from django.db import models

# Create your models here.

tree_structure/employees/forms.py
from django import forms

from employees.models import Worker


class WorkerForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ['full_name',
                  'position',
                  'employment_date',
                  'salary',
                  'parent'
                  ]

tree_structure/employees/views.py
from django.core.paginator import Paginator
from django.shortcuts import HttpResponse, HttpResponseRedirect, render

from employees.forms import WorkerForm
from employees.models import Worker


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def show_employees(request):
    if is_ajax(request=request):
        children_id = request.GET['children_id']
        employee = Worker.objects.get(id=children_id)
        employees = employee.get_descendants(include_self="True").\
            filter(level__lte=employee.level + 3)
        response = render(request,
                          'employees_list.html',
                          {'employees': employees}
                          )
        return response
    else:
        employees = Worker.objects.all().filter(level__lte=1)
        return render(request, "employees.html", {'employees': employees})


def show_employees_all(request):
    if request.user.is_authenticated:
        employees = Worker.objects.order_by('date_added')
        current_page = Paginator(list(employees), 20)
        page_number = request.GET.get('page')
        page = current_page.get_page(page_number)
        return render(request, 'employees_all.html', {
            'paginator': current_page,
            'employees': page,
        })
    else:
        return HttpResponseRedirect("/users/login")


def edit(request, employee_id):
    employee = Worker.objects.get(id=employee_id)
    if request.method != 'POST':
        form = WorkerForm(instance=employee, prefix='form')
        request.session['return_path'] = request.META.get('HTTP_REFERER','/')
    else:
        form = WorkerForm(request.POST, instance=employee, prefix='form')
        if form.is_valid():
            employee = form.save(commit=False)
            employee.save()
        return HttpResponseRedirect(request.session['return_path'])
    context = {'form': form}
    return render(request, 'edit.html', context)


def delete(request, employee_id):
    employee = Worker.objects.get(id=employee_id)
    for child in employee.get_children():
        child.parent = employee.parent
        child.save()
    employee.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def change_boss(request):
    if is_ajax(request=request):
        boss_id = request.GET['boss_id']
        children_id = request.GET['children_id']
        if boss_id == "nestable":
            current_child = Worker.objects.get(id=children_id)
            current_child.move_to(None, 'first-child')
            current_child.save()
        else:
            parent = Worker.objects.get(id=boss_id)
            current_child = Worker.objects.get(id=children_id)
            current_child.move_to(parent, 'first-child')
            current_child.save()
        return HttpResponse('')

tree_structure/users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.base import View
from django.views.generic.edit import FormView


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = reverse_lazy('show_employees')
    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('show_employees')
    template_name = "login.html"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/employees")

tree_structure/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    {% load static %}
    <title>Tree_of_departments</title>
    <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <main>
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <div class="card card-image" style="border: none;">
            <div class="rgba-black-strong py-5 px-4">
              <div class="row d-flex justify-content-center">
                <div class="col-md-10 col-xl-8">
                  <div class="card mb-4">
                    <div class="card-header p-0 z-depth-1">
                      <div class="d-table">
                        <div class="d-tr">
                          <div class="d-td" style="width:60%">
                            <i class="fa fa-cloud fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                            <h4 class="text-uppercase white-text mb-0 py-3 mt-1">
                                {% if user.is_authenticated %}
                                    <a href="{% url 'show_employees_all' %}">employee hierarchy</a>
                                {% else %}
                                    employee hierarchy
                                {% endif %}
                            </h4>
                          </div>
                          <div class="d-td" style="width:20%">
                              {% if user.is_authenticated %}
                                <h4>account: {{ user }}</h4>
                              {% else %}
                                <a href="{% url 'users:register' %}"><h4>REGISTRATION</h4></a>
                              {% endif %}
                          </div>
                          <div class="d-td" style="width:20%">
                              {% if user.is_authenticated %}
                                <a href="{% url 'users:logout' %}"><h4>LOG OUT</h4></a>
                              {% else %}
                                <a href="{% url 'users:login' %}"><h4>LOG IN</h4></a>
                              {% endif %}
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    <main>
</body>
</html>

tree_structure/templates/edit.html
<form method='post' enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" class="submit" value="Upload"></p>
</form>

tree_structure/templates/employees.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static 'js/jquery.nestable.js' %}"></script>
<script src="{% static 'js/uploadchildren.js' %}"></script>
<script src="{% static 'js/getCookie.js' %}"></script>

{% csrf_token %}

{% load mptt_tags %}

<div class="cf nestable-lists">
  <div class="dd" id="nestable">
    <ol class="root dd-list">
      {% recursetree employees %}
        <li class="dd-item" id="{{ node.id }}">
          <div class="dd-handle" id="div{{ node.id }}">{{ node.full_name }}, Position - {{ node.position }}, Salary - {{ node.salary }}</div>
          {% if not node.is_leaf_node %}
            <ol class="children">
                {{ children }}
            </ol>
          {% endif %}
        </li>
      {% endrecursetree %}
    </ol>
  </div>
</div>

{% endblock %}

tree_structure/templates/employees_all.html
{% extends "base.html" %}
{% load static %}

<head>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="/static/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
<script type="text/javascript" src="/static/fancybox/jquery.fancybox.pack.js"></script>
<script type="text/javascript" src="/static/fancybox/script.js"></script>
<link rel="stylesheet" type="text/css" href="/static/fancybox/style.css">
<script src="{% static 'js/sort.js' %}"></script>
<script src="{% static 'js/document_write.js' %}"></script>
</head>

{% block content %}

<div class="rgba-black-strong py-5 px-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8">
            <div class="card-header p-0 z-depth-1">
                <div class="d-table">
                    <div class="d-tr">
                        <div class="d-td" style="width:35%" onclick="search_text('full_name')"><h4>EMPLOYEE NAME</h4></div>
                        <div class="d-td" style="width:15%" onclick="search_text('position')"><h4>POSITION</h4></div>
                        <div class="d-td" style="width:15%" onclick="search_text('employment_date')"><h4>START DATE</h4></div>
                        <div class="d-td" style="width:15%" onclick="search_text('salary')"><h4>SALARY</h4></div>
                        <div class="d-td" style="width:10%"><h4>DELETE</h4></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="div_sort">
    <div class="rgba-black-strong py-0 px-4">
      <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8">
          <div class="card mb-4">
            <div class="card-header p-0 z-depth-1">
                <div class="d-table"><div id="div_sort">
                    {% for employee in employees %}
                        <div class="d-table">
                            <div class="d-tr">
                                <div class="d-td" style="width:35%"><h4><a href="{% url 'edit' employee_id=employee.id %}">{{ employee.full_name }}</a></h4></div>
                                <div class="d-td" style="width:15%"><h4>{{ employee.position }}</h4></div>
                                <div class="d-td" style="width:15%"><h4>{{ employee.employment_date|date:'Y.M.d' }}</h4></div>
                                <div class="d-td" style="width:15%"><h4>{{ employee.salary }}</h4></div>
                                <div class="d-td" style="width:10%"><a href="{% url 'delete' employee_id=employee.id %}"><h4>DELETE</h4></a></div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>



{% if employees.has_other_pages %}
    {% include "paginator.html" with items=employees paginator=paginator geturl=request.GET.urlencode %}
{% endif %}


{% endblock %}

tree_structure/templates/employees_list.html
{% load mptt_tags %}
  {% recursetree employees %}
    <li class="dd-item" id="{{ node.id }}">
        <div class="dd-handle" id="div{{ node.id }}">{{ node.full_name }}, Position - {{ node.position }}, Salary - {{ node.salary }}</div>
          {% if not node.is_leaf_node %}
            <ol class="children">
                {{ children }}
            </ol>
          {% endif %}
    </li>
  {% endrecursetree %}

tree_structure/templates/paginator.html
<nav aria-label="Переключение страниц">
    <ul class="pagination">
        {% if items.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ items.previous_page_number }}&{{geturl}}">&laquo; Предыдущая</a></li>
        {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; Предыдущая</a></li>
        {% endif %}
        {% for i in paginator.page_range %}
                {% if items.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(текущая)</span></span></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}&{{geturl}}">{{ i }}</a></li>
                {% endif %}
        {% endfor %}
        {% if items.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ items.next_page_number }}&{{geturl}}">Следующая &raquo;</a></li>
        {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Следующая &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

tree_structure/users/templates/login.html
<html>
  <head>
    <title>Регистрация</title>
  </head>

  <body>
        <form action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="button">Вход</button>
        </form>
  </body>
</html>

tree_structure/users/templates/register.html
<html>
  <head>
    <title>Регистрация</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Зарегистрироваться</button>
    </form>
  </body>
</html>